### ISSUE TITLE
Skills Management: Add a Skill

### ISSUE THREAD

**Issue by SeanKilleen** [excellalabs/skillustrator#24]
As a user, I want to be able to add a skill, so that I can expand an understanding of my company's skills.

To add a skill, I need to enter the skill name.

**Comment by danstalcup** [comment]
If I'm not mistaken, this feature already exists. Go to "Manage Skills", type in a skill name, and click the "+" sign.

**Comment by danstalcup** [comment]
Closing issue. Feel free to re-open if I'm missing something.
